version: "3.8"

services:
  portfolio-prod:
    build: .
    image: portfolio:latest
    container_name: portfolio-prod
    ports:
      - "8081:8081"
    restart: always
    networks:
      - portfolio-network
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - portfolio-prod
    networks:
      - portfolio-network

networks:
  portfolio-network:
    name: portfolio-network